--------------------------------------------------------
--  File creato - martedì-aprile-03-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MOVIMENTI
--------------------------------------------------------

  CREATE TABLE "DARIO_DB"."MOVIMENTI" 
   (	"ID" NUMBER, 
	"VIN" VARCHAR2(20 BYTE), 
	"COD_MODELLO" VARCHAR2(20 BYTE), 
	"COD_TELAIO" VARCHAR2(20 BYTE), 
	"COD_PIAZZALE" VARCHAR2(5 BYTE), 
	"VERSIONE" VARCHAR2(20 BYTE), 
	"SERIE" VARCHAR2(20 BYTE), 
	"DATA_INSERT" DATE, 
	"DATA_MODIFICA" DATE, 
	"PARKING_SPOT" VARCHAR2(20 BYTE), 
	"NUMBER_PLATE" VARCHAR2(20 BYTE), 
	"TIPO_TRASPORTO" VARCHAR2(20 BYTE), 
	"TIPO_MOVIMENTO" VARCHAR2(20 BYTE), 
	"DATA_MOVIMENTO" DATE, 
	"DATA_DELETE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MOVIMENTI
--------------------------------------------------------

  ALTER TABLE "DARIO_DB"."MOVIMENTI" MODIFY ("DATA_MOVIMENTO" NOT NULL ENABLE);
  ALTER TABLE "DARIO_DB"."MOVIMENTI" MODIFY ("DATA_MODIFICA" NOT NULL ENABLE);
  ALTER TABLE "DARIO_DB"."MOVIMENTI" MODIFY ("DATA_INSERT" NOT NULL ENABLE);
  ALTER TABLE "DARIO_DB"."MOVIMENTI" MODIFY ("SERIE" NOT NULL ENABLE);
  ALTER TABLE "DARIO_DB"."MOVIMENTI" MODIFY ("VERSIONE" NOT NULL ENABLE);
  ALTER TABLE "DARIO_DB"."MOVIMENTI" MODIFY ("COD_PIAZZALE" NOT NULL ENABLE);
  ALTER TABLE "DARIO_DB"."MOVIMENTI" MODIFY ("COD_TELAIO" NOT NULL ENABLE);
  ALTER TABLE "DARIO_DB"."MOVIMENTI" MODIFY ("COD_MODELLO" NOT NULL ENABLE);
  ALTER TABLE "DARIO_DB"."MOVIMENTI" MODIFY ("VIN" NOT NULL ENABLE);
  ALTER TABLE "DARIO_DB"."MOVIMENTI" MODIFY ("ID" NOT NULL ENABLE);
